apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openintegration-shared-volume
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi